notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

build_script:
  - ps: ./build.ps1

artifacts:
  - path: '..\..\cygbuild64\usr\src\minicyg-*.zip'
